PR with errors
AlesiaRebkavets/Hometask_Lec13 pull request #1
Opened 2022-12-18 12:14 UTC by AlesiaRebkavets

2023-01-09 07:54 UTC, ezhukovskaya requested changes

2023-01-09 07:54 UTC, ezhukovskaya commented on BrowserUtils/Browser.cs
> +        public static void SetImplicitlyWait()                          // ImplicitlyWait Timeout is 20 sec
better set comments under the method

2023-01-09 07:54 UTC, ezhukovskaya commented on BrowserUtils/Browser.cs
> +        public static void Quit()                          // closes all browser tabs
if your method contains the only line, convert it to one-line lambda exression

2023-01-09 07:54 UTC, ezhukovskaya commented on Pages/BasePage.cs
> +       private static By _textBoxMenuItemLocator = By.XPath("//ul[@class='menu-list']/li[1]");
you have common part in 6 locators, so wrap it in the const string

2023-01-09 07:54 UTC, ezhukovskaya commented on Pages/BasePage.cs
> +       private static By _checkBoxMenuItemLocator = By.XPath("//ul[@class='menu-list']/li[2]");
better not to use direct tag names like div, ul and etc.
If it possible replace them with * - [XPath Wildcard](https://www.javatpoint.com/xpath-wildcard)

2023-01-09 07:54 UTC, ezhukovskaya commented on Pages/BasePage.cs
> +       private static By _elementsButtonLocator = By.XPath("//div[@class='category-cards']/div[1]");
this is not a good way to find elements via their index, better to find much more flexible locator

2023-01-09 07:54 UTC, ezhukovskaya commented on Pages/ButtonsPage.cs
> +        private static By _clickButtonLocator = By.XPath("//button[text()=\"Click Me\"]");
xpath afford you to use ' instead of ". So no reason to use such exressions as \"

2023-01-09 07:54 UTC, ezhukovskaya commented on Pages/ButtonsPage.cs
> +        public static void OpenButtonsPage()                 // method opens Buttons page
if you open buttons page, maybe its better to return this page?

2023-01-09 07:54 UTC, ezhukovskaya commented on Pages/CheckBoxPage.cs
> +        private static By _homeCollapseButtonLocator = By.XPath("//label[@for=\"tree-node-home\"]/../button");
/../ is not a good way to connect to parent
you can put sth like this `//button[.//@for='tree-node-home']`

2023-01-09 07:54 UTC, ezhukovskaya commented on Pages/LinksPage.cs
> +
empty lines

2023-01-09 07:54 UTC, ezhukovskaya commented on Tests/LinksTest.cs
> +
empty lines

2023-01-11 10:50 UTC, AlesiaRebkavets commented on Pages/CheckBoxPage.cs
> +        private static By _homeCollapseButtonLocator = By.XPath("//label[@for=\"tree-node-home\"]/../button");
corrected

2023-01-11 11:04 UTC, AlesiaRebkavets commented on Pages/ButtonsPage.cs
> +        private static By _clickButtonLocator = By.XPath("//button[text()=\"Click Me\"]");
corrected

2023-01-12 09:04 UTC, AlesiaRebkavets commented on BrowserUtils/Browser.cs
> +        public static void SetImplicitlyWait()                          // ImplicitlyWait Timeout is 20 sec
corrected

2023-01-12 09:04 UTC, AlesiaRebkavets commented on BrowserUtils/Browser.cs
> +        public static void Quit()                          // closes all browser tabs
corrected

2023-01-12 09:04 UTC, AlesiaRebkavets commented on Pages/BasePage.cs
> +       private static By _textBoxMenuItemLocator = By.XPath("//ul[@class='menu-list']/li[1]");
Corrected, but after that BasePage class was deleted.

2023-01-12 09:05 UTC, AlesiaRebkavets commented on Pages/BasePage.cs
> +       private static By _checkBoxMenuItemLocator = By.XPath("//ul[@class='menu-list']/li[2]");
BasePage класс пришлось удалить за ненадобностью после других коррекшенов (стала открывать стрицы без лишнего нажатия кнопок, используя урлу), но исправила это в других классах.

2023-01-12 09:05 UTC, AlesiaRebkavets commented on Pages/BasePage.cs
> +       private static By _elementsButtonLocator = By.XPath("//div[@class='category-cards']/div[1]");
BasePage класс пришлось удалить за ненадобностью после других коррекшенов (стала открывать стрицы без лишнего нажатия кнопок, используя урлу), но исправила это в других классах.

2023-01-12 09:05 UTC, AlesiaRebkavets commented on Pages/ButtonsPage.cs
> +        public static void OpenButtonsPage()                 // method opens Buttons page
corrected for all pages

2023-01-12 09:06 UTC, AlesiaRebkavets commented on Pages/LinksPage.cs
> +
corrected

2023-01-12 09:06 UTC, AlesiaRebkavets commented on Tests/LinksTest.cs
> +
corrected

2023-01-12 09:23 UTC, ezhukovskaya requested changes

2023-01-12 09:23 UTC, ezhukovskaya commented on Pages/CheckBoxPage.cs
> +        private static By _homeCollapseButtonLocator = By.XPath("//button[..//@for='tree-node-home']");
use wildcards

2023-01-12 09:23 UTC, ezhukovskaya commented on Pages/RadioButtonPage.cs
> +        private static By _impressiveRadioButtonLocator = By.XPath("//label[text()='Impressive']");
use wildcards

2023-01-12 09:23 UTC, ezhukovskaya commented on Pages/LinksPage.cs
> +    public class LinksPage: Browser
Page must inherit only BasePage

2023-01-12 09:23 UTC, ezhukovskaya commented on Pages/LinksPage.cs
> +        private const string LinksPageUrl = "https://demoqa.com/links";
you declare url in each class, create Url field in BasePage and set it in constructor as parameter via calling base constructor

2023-01-12 09:23 UTC, ezhukovskaya commented on Pages/WebTablesPage.cs
> +            By.XPath("//*[@role=\"rowgroup\"][4]//*[@role=\"gridcell\"][1]");
is there any way to avoid using indexes?

2023-01-15 15:26 UTC, AlesiaRebkavets commented on Pages/WebTablesPage.cs
> +            By.XPath("//*[@role=\"rowgroup\"][4]//*[@role=\"gridcell\"][1]");
тут индекс - лучший вариант, так как мы работаем с таблицей. При помощи индексов я перебираю 1-6 столбцы 4-й строки.

2023-01-15 15:27 UTC, AlesiaRebkavets commented on Pages/LinksPage.cs
> +        private const string LinksPageUrl = "https://demoqa.com/links";
corrected

2023-01-15 15:27 UTC, AlesiaRebkavets commented on Pages/LinksPage.cs
> +    public class LinksPage: Browser
corrected

2023-01-15 15:28 UTC, AlesiaRebkavets commented on Pages/RadioButtonPage.cs
> +        private static By _impressiveRadioButtonLocator = By.XPath("//label[text()='Impressive']");
corrected

2023-01-15 15:29 UTC, AlesiaRebkavets commented on Pages/CheckBoxPage.cs
> +        private static By _homeCollapseButtonLocator = By.XPath("//button[..//@for='tree-node-home']");
corrected

2023-01-16 07:48 UTC, ezhukovskaya approved these changes

2023-02-17 11:30 UTC, merged